# M1A2 - Manipulação de arrays com NumPy

Nessa aula iremos aprender como manipular matriz e vetores utilizando [NumPY](https://numpy.org/)

Esse notebook está estruturado da seguinte forma.

- Instalação
- Operações básicas com vetores
- Operaçõões básicas com matrizes
- Próximos passos
- Atividade Complementares

## Instalação e Importação da Biblioteca

In [19]:
!pip install numpy

In [20]:
import numpy as np

## Operações Básicas com Vetores

Primeiro vamos criar vetores para que possamos entender como eles são representados, e como podemos manipular eles. 

Nesse exemplos, vamos utilizar os vetores $\vec{u}$ e $\vec{v}$ com coordenadas $(1, 3)$ e $(3, 1)$ respectivamente como ilustrado na imagem abaixo.

![vetores u e v](vetores.png)

In [21]:
# Criando vetores.
u = np.array([1, 3])
v = np.array([3, 1])

Operações feitas individualmente nas dimensões do vetores como substração e adição podem ser feitas utilizando os operadores $-$ e $+$.

In [22]:
y = u - v
w = u + v

print(f"Vetor y: {y}\nVetor w: {w}")

Vetor y: [-2  2]
Vetor w: [4 4]


Analogamente podemos visualizar esses resultados no plano cartesiano.

![subtração e adição com u e v](sub-add-vecs.png)

Multiplicação e divisão são feitas elemento por elemento.

Com essa multiplicação podemos realizar o produto escalar, por exemplo $\alpha * \vec{u}$

In [23]:
a = u / v
b = u * v

print(f"Vetor a: {a}\nVetor b: {b}")

alpha = 2
escalar = alpha * u
print(f"Produtor escalar de u por alpha: {escalar}")

Vetor a: [0.33333333 3.        ]
Vetor b: [3 3]
Produtor escalar de u por alpha: [2 6]


Também é possível realizar operações geométrica como produto interno e vetorial.

In [24]:
interno = np.dot(u, v)


# Para o produto vetorial iremos utilizar vetores tridimensionais.
u3 = np.array([1, 3, 1])
v3 = np.array([3, 1, 1])
vetorial = np.cross(u3, v3)

print(f"Resultado produto interno: {interno}\nResutlado produto vetorial: {vetorial}")

Resultado produto interno: 6
Resutlado produto vetorial: [ 2  2 -8]


## Operações Básicas com Matrizes

A primeira coisa a compreender é como representar matrizes. Analogamente a vetores, em NumPy matrizes são vetores bidimesionais.

Vamos fazer alguns exemplos e observar que podemos reproduzir todas as operações.

In [16]:
I = np.array([[1, 0],[0, 1]])
A = np.array([[2, 1],[1, 2]])

De maneira semelhante quando utilizamos vetores as operações podem ser realizadas elemento a elemento, ou seguindo a algebra que estamos familiarizados.

In [25]:
B = A + I

print(f"Matriz A:\n{A}\n\nMatriz Identidade:\n{I}\n\nMatriz B = A + I:\n{B}")

Matriz A:
[[2 1]
 [1 2]]

Matriz Identidade:
[[1 0]
 [0 1]]

Matriz B = A + I:
[[3 1]
 [1 3]]


In [26]:
B = A - I

print(f"Matriz A:\n{A}\n\nMatriz Identidade:\n{I}\n\nMatriz B = A - I:\n{B}")

Matriz A:
[[2 1]
 [1 2]]

Matriz Identidade:
[[1 0]
 [0 1]]

Matriz B = A - I:
[[1 1]
 [1 1]]


Os operadores não precisam nem ter exatamente as mesmas dimensões.

In [30]:
C = A + u

print(f"Matriz A:\n{A}\nVetor u:\n{u}\n\nMatriz C = A + u:\n{C}")

Matriz A:
[[2 1]
 [1 2]]
Vetor u:
[1 3]

Matriz C = A + u:
[[3 4]
 [2 5]]


Para realizarmos a multiplicação de matrizes também podemos utilizar NumPy. Desde que observe-se a regra de colunas e linhas compatíveis entre os operadores.

In [28]:
D = np.matmul(A, I)

print(f"Matriz A:\n{A}\n\nMatriz Identidade:\n{I}\n\nMatriz D = A x I:\n{D}")

Matriz A:
[[2 1]
 [1 2]]

Matriz Identidade:
[[1 0]
 [0 1]]

Matriz D = A x I:
[[2 1]
 [1 2]]


## Próximos Passos e Referências

Nas próximas aulas iremos compreender como essa estrutura de dados e operações fornecidas pela biblioteca NumPy são funcionais para os problemas comuns em Visão Computacional.

Uma lista não exaustiva de referências segue:

- https://numpy.org/devdocs/user/absolute_beginners.html
- https://www.geogebra.org/
- https://numpy.org/devdocs/user/whatisnumpy.html
- https://numpy.org/devdocs/user/quickstart.html

## Atividades Complementares (Opicional)

Faça operações com outras matrizes.

- [ ] Existe outra forma de instaciar matrizes e vetores especiais (matriz identidade, vetor nulo, etc)?
- [ ] Existe outra forma de realizar as operações que chamamos da biblioteca (np.dot, np.matmul)?
- [ ] É possível trabalhar com arrays multi-dimensionais? Faça alguns testes com vetores e matrizes 3D.